site_name: Football Pipeline Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
  language: en
  icon:
    admonition:
      info: fontawesome/solid/code
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: green
plugins:
  - search
  - exclude:
      glob:
      # - _hidden_pages/*
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          options:
            heading_level: 3
            show_private_members: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andrefelippevidal/

markdown_extensions:
  - markdown_include.include
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2  # This controls what level of headers shows up in navigation
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
repo_url: https://github.com/andrefelippevidal
repo_name: football-project
copyright: |
  &copy; 2024 <a href="https://www.linkedin.com/in/andrefelippevidal/"  target="_blank" rel="noopener">André Vidal</a>