models:
  - name: mart_fbs__competitions
    description: Competitions overview data mart, offering one row per competition with some summarized values.
    columns:
      - name: competition_id
        description: The foreign key relating to the competition who the data belongs to.
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_fb__competitions')
              field: competition_id
      - name: competition_name
        description: Name of the competition
      - name: teams_count
        description: The count of the teams that belongs to that competition
      - name: last_updated_in_source
        description: The timestamp the competition was last updated.

unit_tests:
  - name: test_campeonato_brasileiro_team_count
    description: "Test that the counts of teams that belongs to campeonato brasileiro."
    model: mart_fbs__competitions
    given:
      - input: ref('stg_fb__teams')
        rows:
          - {
              competition_id: 2013,
              team_id: 1
            }
          - {
              competition_id: 2013,
              team_id: 2
            }
          - {
              competition_id: 2013,
              team_id: 3
            }
      - input: ref('stg_fb__competitions')
        rows:
          - { 
              competition_id: 2013,
              competition_name: 'Campeonato Brasileiro' 
            }
    expect:
      rows:
        - {
            competition_id: 2013,
            competition_name: 'Campeonato Brasileiro',
            teams_count: 3,
          }
