dbt_football:
  outputs:
    dev:
      dbname: "{{ env_var('PG_DB') }}"
      host: "{{ env_var('PG_HOST') }}"
      pass: "{{ env_var('PG_PASS') }}"
      port: 5432
      schema: "{{ env_var('PG_SCHEMA') }}"
      threads: "{{ env_var('PG_THREADS') | int }}"
      type: postgres
      user: "{{ env_var('PG_USER') }}"
  target: dev